$(document).ready(function () {

		        pageSetUp();
		        var _gaq = _gaq || [];
		        _gaq.push(['_setAccount', 'UA-XXXXXXXX-X']);
		        _gaq.push(['_trackPageview']);

		        /* // DOM Position key index //
                
                    l - Length changing (dropdown)
                    f - Filtering input (search)
                    t - The Table! (datatable)
                    i - Information (records)
                    p - Pagination (paging)
                    r - pRocessing 
                    < and > - div elements
                    <"#id" and > - div with an id
                    <"class" and > - div with a class
                    <"#id.class" and > - div with an id and class
                    
                    Also see: http://legacy.datatables.net/usage/features
                */

		        /* BASIC ;*/

		        $('#dt_basic').dataTable();


		        /* END BASIC */

		        /* COLUMN FILTER  */
		        var otable = $('#datatable_fixed_column').DataTable({
		            //"bFilter": false,
		            //"bInfo": false,
		            //"bLengthChange": false
		            //"bAutoWidth": false,
		            //"bPaginate": false,
		            //"bStateSave": true // saves sort state using localStorage
		            "sDom": "<'dt-toolbar'<'col-xs-6'f><'col-xs-6'<'toolbar'>>r>" +
                            "t" +
                            "<'dt-toolbar-footer'<'col-xs-6'i><'col-xs-6'p>>"

		        });

		        // custom toolbar
		        $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

		        // Apply the filter
		        $("#datatable_fixed_column thead th input[type=text]").on('keyup change', function () {

		            otable
                        .column($(this).parent().index() + ':visible')
                        .search(this.value)
                        .draw();

		        });
		        /* END COLUMN FILTER */

		        /* COLUMN SHOW - HIDE */
		        $('#datatable_col_reorder').dataTable({
		            "sDom": "<'dt-toolbar'<'col-xs-6'f><'col-xs-6'C>r>" +
                            "t" +
                            "<'dt-toolbar-footer'<'col-xs-6'i><'col-xs-6'p>>"
		        });

		        /* END COLUMN SHOW - HIDE */

		        /* TABLETOOLS */
		        $('#datatable_tabletools').dataTable({

		            // Tabletools options: 
		            //   https://datatables.net/extensions/tabletools/button_options
		            "sDom": "<'dt-toolbar'<'col-xs-6'f><'col-xs-6'T>r>" +
                            "t" +
                            "<'dt-toolbar-footer'<'col-xs-6'i><'col-xs-6'p>>",
		            "oTableTools": {
		                "aButtons": [
                        "copy",
                        "csv",
                        "xls",
                           {
                               "sExtends": "pdf",
                               "sTitle": "SmartAdmin_PDF",
                               "sPdfMessage": "SmartAdmin PDF Export",
                               "sPdfSize": "letter"
                           },
                           {
                               "sExtends": "print",
                               "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                           }
		                ],
		                "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
		            }
		        });

		        /* END TABLETOOLS */

		    })


		
(function () {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
})();

function activaDesactiva(idusuario)
{
    var estadoActual = parseInt($("#chEstado").val());
    var cambiarestado;
    if (estadoActual == 0)
    {
        cambiarestado = 1;
    }
    else
    {
        cambiarestado = 0;
    }

    $.post("administracion.aspx", {
        action:"cambiaEstado",cambiarEstado:cambiarestado,idUsuario:idusuario
    }, function (data)
    {
        data = data.split("//");
        if (data[1] == "OK") {
            alert(data[2]);
            location.href = "/administracion.aspx";
        }
        else
        {
            alert(data[2]);
        }
    })
}
function cerrarSesion()
{
    $.post("administracion.aspx", {
        action:"cierraSesion"
    },function(data)
    {

    })
}

function eliminaUsuario(idUsuario)
{
    if (confirm("estas seguro de eliminar este usuario")) {
        $.post("administracion.aspx", {
            action: "eliminaUSuario", idUsuario: idUsuario
        }, function (data) {
            data = data.split("//");
            if (data[1] == "OK") {
                alert(data[2]);
                location.href = "/administracion.aspx";
            }
            else {
                alert(data[2]);
            }
        })
    }
    else
    {
        return;
    }
}